name: Deploy Maven Artifacts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Deploy Maven Artifacts with Debugging
        run: |
          ./mvnw deploy -DaltDeploymentRepository=github-repo::default::https://spigotrce.github.io/maven-repo/ -X
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
